# Generated by Django 4.2.1 on 2023-05-21 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nrumber', models.CharField(max_length=2, verbose_name='НОМrЕР')),
                ('troday_status', models.CharField(max_length=8, verbose_name='СЕГrОДНЯ')),
                ('tormorrow_status', models.CharField(max_length=8, verbose_name='ЗАВrТРА')),
            ],
            options={
                'verbose_name': 'номер',
                'verbose_name_plural': 'Номера',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50, verbose_name='ИМЯ')),
                ('email', models.CharField(max_length=50, verbose_name='ПОЧТА')),
                ('password', models.CharField(max_length=50, verbose_name='ПАРОЛЬ')),
            ],
            options={
                'verbose_name': 'профиль пользователя',
                'verbose_name_plural': 'Зарегистрированные пользователи',
            },
        ),
    ]
